In [12]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
wine=pd.read_csv('Wine.csv')

In [14]:
wine.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [15]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
Alcohol                 178 non-null float64
Malic_Acid              178 non-null float64
Ash                     178 non-null float64
Ash_Alcanity            178 non-null float64
Magnesium               178 non-null int64
Total_Phenols           178 non-null float64
Flavanoids              178 non-null float64
Nonflavanoid_Phenols    178 non-null float64
Proanthocyanins         178 non-null float64
Color_Intensity         178 non-null float64
Hue                     178 non-null float64
OD280                   178 non-null float64
Proline                 178 non-null int64
Customer_Segment        178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.5 KB


In [16]:
from sklearn.preprocessing import StandardScaler
wine = StandardScaler().fit_transform(wine)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [17]:
mean_vec = np.mean(wine, axis=0)

In [18]:
cov_mat = np.cov(wine.T)

In [21]:
cov_mat

array([[ 1.00564972,  0.09493026,  0.21273976, -0.31198788,  0.27232816,
         0.29073446,  0.23815287, -0.15681042,  0.13747022,  0.549451  ,
        -0.07215255,  0.07275191,  0.64735687, -0.3300763 ],
       [ 0.09493026,  1.00564972,  0.16497228,  0.29013035, -0.05488343,
        -0.3370606 , -0.41332866,  0.29463237, -0.22199334,  0.25039204,
        -0.56446685, -0.37079354, -0.19309537,  0.44024952],
       [ 0.21273976,  0.16497228,  1.00564972,  0.44587209,  0.28820583,
         0.12970824,  0.11572743,  0.1872826 ,  0.00970647,  0.2603499 ,
        -0.07508874,  0.00393333,  0.22488969, -0.04992369],
       [-0.31198788,  0.29013035,  0.44587209,  1.00564972, -0.0838039 ,
        -0.32292752, -0.353355  ,  0.36396647, -0.19844168,  0.01883781,
        -0.27550299, -0.27833221, -0.44308618,  0.52078487],
       [ 0.27232816, -0.05488343,  0.28820583, -0.0838039 ,  1.00564972,
         0.21561254,  0.19688989, -0.25774204,  0.23777643,  0.20107967,
         0.05571118,  0.06

In [22]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

In [24]:
eig_vals

array([5.56722458, 2.51118402, 1.45424413, 0.9331603 , 0.88246016,
       0.67657935, 0.55692777, 0.05813894, 0.35201176, 0.13029618,
       0.16975037, 0.29620602, 0.2271244 , 0.26378805])

In [25]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

In [26]:
eig_pairs

[(5.567224581550709,
  array([-0.13632501,  0.22267638, -0.00225793,  0.22429849, -0.12463016,
         -0.35926404, -0.39071171,  0.2670012 , -0.2790625 ,  0.08931829,
         -0.27682265, -0.35052618, -0.26951525,  0.39366953])),
 (2.511184022569786,
  array([-0.48416087, -0.22359095, -0.31585588,  0.01161574, -0.30055143,
         -0.06711983,  0.00131345, -0.0269887 , -0.04122256, -0.52978274,
          0.27790735,  0.16277625, -0.36605886, -0.00569041])),
 (1.4542441334626712,
  array([ 0.20740081, -0.08879606, -0.62610236, -0.6119896 , -0.13098458,
         -0.14650775, -0.15096275, -0.16997551, -0.14987959,  0.1372663 ,
         -0.08532854, -0.16620436,  0.12668685, -0.00121795])),
 (0.9331603017536697,
  array([ 0.08191848, -0.46988824,  0.24984122, -0.07199322,  0.16321412,
         -0.19098521, -0.14461667,  0.32801272, -0.46275771, -0.07211248,
          0.43466618, -0.15672341,  0.2557949 , -0.12246373])),
 (0.8824601592424326,
  array([ 0.25089415,  0.18860015,  0.093523

In [27]:
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [28]:
eig_pairs

[(5.567224581550709,
  array([-0.13632501,  0.22267638, -0.00225793,  0.22429849, -0.12463016,
         -0.35926404, -0.39071171,  0.2670012 , -0.2790625 ,  0.08931829,
         -0.27682265, -0.35052618, -0.26951525,  0.39366953])),
 (2.511184022569786,
  array([-0.48416087, -0.22359095, -0.31585588,  0.01161574, -0.30055143,
         -0.06711983,  0.00131345, -0.0269887 , -0.04122256, -0.52978274,
          0.27790735,  0.16277625, -0.36605886, -0.00569041])),
 (1.4542441334626712,
  array([ 0.20740081, -0.08879606, -0.62610236, -0.6119896 , -0.13098458,
         -0.14650775, -0.15096275, -0.16997551, -0.14987959,  0.1372663 ,
         -0.08532854, -0.16620436,  0.12668685, -0.00121795])),
 (0.9331603017536697,
  array([ 0.08191848, -0.46988824,  0.24984122, -0.07199322,  0.16321412,
         -0.19098521, -0.14461667,  0.32801272, -0.46275771, -0.07211248,
          0.43466618, -0.15672341,  0.2557949 , -0.12246373])),
 (0.8824601592424326,
  array([ 0.25089415,  0.18860015,  0.093523

In [29]:
exp_var_percentage = 0.97 

In [30]:
tot = sum(eig_vals)

In [31]:
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

In [32]:
num_vec_to_keep = 0

In [34]:
for index, percentage in enumerate(cum_var_exp):
    if percentage > exp_var_percentage:
        num_vec_to_keep = index + 1
        break

In [35]:
num_features = wine.shape[1]

In [36]:
proj_mat = eig_pairs[0][1].reshape(num_features,1)

In [37]:
for eig_vec_idx in range(1, num_vec_to_keep):
    proj_mat = np.hstack((proj_mat, eig_pairs[eig_vec_idx][1].reshape(num_features,1)))


In [38]:
pca_data = wine.dot(proj_mat)